version: '3.8'
services:
  node1:
    build: .
    container_name: node1
    ports:
      - "2222:22"   # SSH
      - "8081:80"   # HTTP nginx
  node2:
    build: .
    container_name: node2
    ports:
      - "2223:22"   # SSH
      - "8082:80"   # HTTP nginx